### ISSUE TITLE
Destination not written because no source files were provided.

### ISSUE THREAD

**Issue by oninross** [bezoerb/grunt-php2html#11]
I have the following in my grunt file but I get the error.  This however works on a Windows Platform.  
```
php2html: {
    default: {
        options: {
            // relative links should be renamed from .php to .html
            processLinks: true,
            htmlhint: false
        },
        files: [
            { expand: true, cwd: 'dist/*', src: ['**/*.php'], dest: 'dist/', ext: '.html' }
        ]
    }
}
```

Any ideas?

**Comment by oninross** [comment]
**Update**

It wasn't working in Windows.  My bad.  I just added in the docroot and a little bit of editing the paths.  But still doesnt work on Mac.  New error though "Resulting HTML is empty".  Only happens in Mac.  Windows work great.

```
php2html: {
    default: {
        options: {
            // relative links should be renamed from .php to .html
            processLinks: true,
            htmlhint: false,
            docroot: 'dist'
        },
        files: [
            { expand: true, cwd: 'dist', src: ['**/*.php'], dest: 'dist', ext: '.html' }
        ]
    }
}
```
Any ideas?

**Comment by bezoerb** [comment]
Can you confirm you have `php-cgi` installed and in your PATH?
Try `php-cgi --version`

**Comment by oninross** [comment]
Just realized that also.  It's working like a charm.  My bad.  Didnt read the instructions properly.  

Thanks though :)
