### ISSUE TITLE
How change hardcoded host value?

### ISSUE THREAD

**Issue by ncer** [bezoerb/grunt-php2html#15]
Hey,

In my project I use `<base href="http://<?=$_SERVER["SERVER_NAME"]?>"/>` and in output html files at my local machine I see `<base href="http://127.0.0.1"/>`. These html files are needed only to production version (development in php) and that's no good to see http://127.0.0.1 on production :)

How can I change a hardcoded host value 127.0.0.1 to custom one?

**Comment by bezoerb** [comment]
Just patched [`php2html`] 
Will bump this module as well as `gulp-php2html` in the next days

**Comment by bezoerb** [comment]
Fixed in [v0.3.0](https://github.com/bezoerb/grunt-php2html/releases/tag/v0.3.0)

**Comment by bezoerb** [comment]
No complaints so the patch seems to work out. 
Feel free to reopen if the error still occurs.
