### ISSUE TITLE
[L##:C##] The value of attribute [ XXX ] must closed by double quotes

### ISSUE THREAD

**Issue by Dan503** [bezoerb/grunt-php2html#9]
The error:
http://grabilla.com/05219-65ecfb18-bf86-40c9-887d-81680fb03f2e.png

Part of the file I'm compiling:
http://grabilla.com/05219-5be4cb33-20ca-48c0-8933-850b780190ef.png

The top of the header.php file if that makes a difference:
http://grabilla.com/05219-8c9475c5-9504-49a4-8fc2-1cc4a031e034.png

Any ideas what the error wants me to do?

**Comment by bezoerb** [comment]
The php file looks correct but the resulting html is checked by `htmlhint`.
Can you also post the part of the resulting html? So i can take a look what's causing this errors.

**Comment by Dan503** [comment]
Ahh never mind, I figured out what the error meant.

The L and C stand for "Line" and "column" in the generated html file.

I looked up the line references and the attributes are only using single quotes instead of double quotes.

using the haltOnError: false, option forced the compilation and it's working now :smile: 

I should clean up those single quotes but I don't really have time right now.

Thanks for responding quickly though :)

**Comment by bezoerb** [comment]
I think you can ignore those warnings by setting the option to false:
https://github.com/yaniswang/HTMLHint/wiki/Attr-value-double-quotes
```javascript
php2html: {
    options: {
        htmlhint: {
            'attr-value-double-quotes': false
        }
    }
}
```

**Comment by Dan503** [comment]
Cool, not getting the error messages any more. Thanks :smile:
